name: Generate Semantic Release
on:
  push:
    branches:
<<<<<<< HEAD
      - version-15
=======
      - version-13
>>>>>>> 325b20491a (fix: make rate of depreciation mandatory)
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Entire Repository
<<<<<<< HEAD
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

=======
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
>>>>>>> 325b20491a (fix: make rate of depreciation mandatory)
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
<<<<<<< HEAD

=======
>>>>>>> 325b20491a (fix: make rate of depreciation mandatory)
      - name: Setup dependencies
        run: |
          npm install @semantic-release/git @semantic-release/exec --no-save
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: "Frappe PR Bot"
          GIT_AUTHOR_EMAIL: "developers@frappe.io"
          GIT_COMMITTER_NAME: "Frappe PR Bot"
          GIT_COMMITTER_EMAIL: "developers@frappe.io"
        run: npx semantic-release
